name: 'coverage'
on:
    pull_request:
        paths-ignore:
            - '**.md'
            - '.*.yml'
jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: artiomtr/jest-coverage-report-action@v1.3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}